{% set name = "homeassistant" %}
{% set version = "2022.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/homeassistant-{{ version }}.tar.gz
  sha256: 9c8c616481eb09cfe5fea8db2b6d95ce28507df7f98e3301b6b118e764ea4556
  patches:
    - cryptography.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - hass = homeassistant.__main__:main

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools
  run:
    - aiohttp ==3.8.1
    - astral ==2.2
    - async-timeout ==4.0.2
    - attrs ==21.2.0
    - awesomeversion ==22.5.2
    - backports.zoneinfo
    - bcrypt ==3.2.0
    - certifi >=2021.5.30
    - ciso8601 ==2.2.0
    - cryptography ==36.0.2
    - httpx ==0.23.0
    - jinja2 ==3.1.2
    - pyjwt ==2.4.0
    - python >=3.9
    - pip <22.2,>=21.0
    - python-slugify ==4.0.1
    - pyyaml ==6.0
    - requests ==2.27.1
    - voluptuous ==0.13.1
    - voluptuous-serialize ==2.5.0
    - yarl ==1.7.2
    - ifaddr ==0.1.7
    - atomicwrites ==1.4.0

test:
  imports:
    - homeassistant
  commands:
    - pip check
    - hass --help
  requires:
    - pip

about:
  home: https://www.home-assistant.io/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: Open source home automation that puts local control and privacy first.
  description: |
    Open source home automation that puts local control and privacy first.
    Powered by a worldwide community of tinkerers and DIY enthusiasts.
    Perfect to run on a Raspberry Pi or a local server.
  doc_url: https://simplejson.readthedocs.io/
  dev_url: https://github.com/home-assistant/core

extra:
  recipe-maintainers:
    - jan-janssen
